### ISSUE TITLE
Can't use Nuke-Alomofire-Plugin with Nuke-webP-plugin

### ISSUE THREAD

**Issue by elimence** [kean/Nuke-Alamofire-Plugin#11]
I tried installing this plugin in my project which already has `nuke-alamofire-plugin`. Looks like they have different requirements for Nuke. Here's the output from running `pod install`

```
[!] CocoaPods could not find compatible versions for pod "Nuke":
  In snapshot (Podfile.lock):
    Nuke (= 5.1.1, ~> 5.0)

  In Podfile:
    Nuke-Alamofire-Plugin was resolved to 2.0, which depends on
      Nuke (~> 5.0)

    Nuke-WebP-Plugin was resolved to 1.1.0, which depends on
      Nuke (~> 6.0)
```

Is there a way around this? All webP images in my app are not loading currently, I'd be grateful for any help, thanks :)

**Comment by kean** [comment]
Sorry, missed this. All Nuke extensions now have Nuke ~> 7.0 dependency including Alamofire and WebP plugins.
