### ISSUE TITLE
Compatibility with Nuke 7?

### ISSUE THREAD

**Issue by roadrunner15** [kean/Nuke-Alamofire-Plugin#12]
Since Nuke ~7 the example from the documentation (README.md; see below) doesn't work anymore since Nuke.Loader and Nuke.Manager are deprecated?

How to set the Alamofire loader with Nuke v7?

Thx

```
let loader = Nuke.Loader(loader: NukeAlamofirePlugin.AlamofireDataLoader())
let manager = Nuke.Manager(loader: loader, cache: Cache.shared)

manager.loadImage(with: url, into: imageView)
```

**Comment by pkurzok** [comment]
From reading Nuke's Documentation I unterstand what you need to do is the following:
`let pipeline = ImagePipeline {
                $0.dataLoader = NukeAlamofirePlugin.AlamofireDataLoader()
                $0.imageCache = ImageCache.shared
        }
        
        ImagePipeline.shared = pipeline`

**Comment by kean** [comment]
Thank you, @pkurzok. I updated the README.
