### ISSUE TITLE
Skipped building Nuke-Alamofire-Plugin

### ISSUE THREAD

**Issue by benjaminths** [kean/Nuke-Alamofire-Plugin#14]
Hi, i can't build Nuke-Alamofire-Plugin.

````*** Skipped building Nuke-Alamofire-Plugin due to the error:
Dependency "Nuke-Alamofire-Plugin" has no shared framework schemes for any of the platforms: iOS

If you believe this to be an error, please file an issue with the maintainers at https://github.com/kean/Nuke-Alamofire-Plugin/issues/new```

**Comment by ElonPark** [comment]
Also, can't build using this `github "kean/NukeAlamofirePlugin"`

```
A shell task (/usr/bin/env git clone --bare --quiet https://github.com/kean/NukeAlamofirePlugin.git ~/Library/Caches/org.carthage.CarthageKit/dependencies/NukeAlamofirePlugin) failed with exit code 128:
remote: Repository not found.
fatal: repository 'https://github.com/kean/NukeAlamofirePlugin.git/' not found
```

**Comment by ElonPark** [comment]
@kean need help!

**Comment by kean** [comment]
@ElonPark please make sure you are using latest Carthage version. 

https://github.com/kean/NukeAlamofirePlugin.git - this is not the correct URL, it should be https://github.com/kean/Nuke-Alamofire-Plugin.git

**Comment by ElonPark** [comment]
> Thanks for the update, @ElonPark. My bad, fixed in https://github.com/kean/Nuke-Alamofire-Plugin/releases/tag/5.0.1

@kean Thanks for the quick fix. And
Thanks for making a great library.
