### ISSUE TITLE
Issue with AlamofireNetworkActivityIndicator?

### ISSUE THREAD

**Issue by winkelsdorf** [kean/Nuke-Alamofire-Plugin#4]
I am trying to route all traffic through Alamofire, for testing I have this in AppDelegate's  ```didFinishLaunchingWithOptions```:

```
        // Automatically show Network Activity Indicator when using Alamofire
        NetworkActivityIndicatorManager.sharedManager.startDelay = 0
        NetworkActivityIndicatorManager.sharedManager.isEnabled = true

        // Redirect Nuke through Alamofire, but use an additional alamoFireManager
        // TODO: Move to Extension..
        let configuration = NSURLSessionConfiguration.defaultSessionConfiguration()
        configuration.HTTPAdditionalHeaders = Manager.defaultHTTPHeaders

        let alamoFireManager = Manager.init(configuration: configuration)
        let dataLoader: ImageDataLoading = AlamofireImageDataLoader(manager: alamoFireManager)
        ImageManager.shared = ImageManager(configuration: ImageManagerConfiguration(dataLoader: dataLoader))
```

Nuke is correctly using the ```alamoFireManager``` in it's calls.

But the NetworkActivityIndicatorManager does not work, no Notifications are sent by Alamofire for .resume.

In Alamofire Request.swift I set a breakpoint for resume() 
```
    public func resume() {
        if startTime == nil { startTime = CFAbsoluteTimeGetCurrent() }

        task.resume()
        NSNotificationCenter.defaultCenter().postNotificationName(Notifications.Task.DidResume, object: task)
    }
```

The call to ```postNotificationName()``` is never reached. I did issue a ```        nk_imageLoadingController.manager.removeAllCachedImages()``` before using ```nk_setImageWith()``` and also tried resetting the simulator.

Edit:
Even with dataLoad set to AlamoFire, Nuke's execute() in Internal.swift uses NSURLSession
```
    func execute() {
        executing = false
        if let task = pendingTasks.firstObject as? NSURLSessionTask where executingTasks.count < maxExecutingTaskCount {
            pendingTasks.removeObjectAtIndex(0)
            executingTasks.insert(task)
            task.resume() // points to NSURLSession
            setNeedsExecute()
        }
    }
```

Any idea what's going on?

**Comment by kean** [comment]
Instead of calling `-resume()` method on `Alamofire.Request` Nuke calls it on an underlying `NSURLSessionTask`. The `Alamofire.Notifications.Task.DidResume` doesn't get fired and that's what `AlamofireNetworkActivityIdicator` listens to.

`-resume()` method on `Alamofire.Request` used to be just a shortcut before, which was really nice.

<img width="1178" alt="screen shot 2016-04-09 at 18 03 15" src="https://cloud.githubusercontent.com/assets/1567433/14404413/6f574e4c-fe86-11e5-9e69-1529d15aaed6.png">

I can't think of a quick fix for that issue right now.

**Comment by kean** [comment]
Apparently, I would eventually have to add a new protocol with a subset of `NSURLSessionTask` methods and use it instead of using `NSURLSessionTask` directly. `Alamofire.Request` would also conform to this protocol.

I'm reluctant to make this change though, just like with any change that bloats the framework.

**Comment by winkelsdorf** [comment]
Ah I see, thus you didn't invoke the stub.. Thanks for checking!

Hmm, making use AlamofireNetworkActivityIndicator would be nice, but I agree not to a point where Nuke get's bloated by. But do you need to extend the Nuke framework itself or can it be done in this repo? If the latter, it would make sense to be able to integrate the Alamofire calls.

**Comment by kean** [comment]
You need to extend core framework.

Image data is loaded via an object conforming to this protocol:
```swift
public protocol ImageDataLoading {
    /// Creates task with a given request. Task is resumed by the object calling the method.
    public func taskWith(request: Nuke.ImageRequest, progress: Nuke.ImageDataLoadingProgress, completion: Nuke.ImageDataLoadingCompletion) -> NSURLSessionTask
}
```

And here's how it's implemented in `AlamofireImageDataLoader`:

```swift
public func taskWith(request: ImageRequest, progress: ImageDataLoadingProgress, completion: ImageDataLoadingCompletion) -> NSURLSessionTask {
    let task = self.manager.request(request.URLRequest).response { (_, response, data, error) -> Void in
        completion(data: data, response: response, error: error)
    }.progress { (_, totalBytesReceived, totalBytesExpected) -> Void in
        progress(completed: totalBytesReceived, total: totalBytesExpected)
    }
   //  I use the fact that you don't need to hold a strong reference to `Alamofire.Request`
    return task.task
}
```

`Alamofire.Request` is only used inside `AlamofireImageDataLoader`, it is not available anywhere else, only the underlying `NSURLSessionTask` is. You can't access `Alamofire.Request` from `Nuke.TaskQueue`.

**Comment by winkelsdorf** [comment]
Saw that right now. NSURLSessionTask is fine, from what I see you are giving the possibility to use what's needed from Alamofire: The configuration and cache.

Don't you have callbacks for the States?

AlamofireNetworkActivityIndicator supports receiving notifications, from their repo 
> Can Support NSURLSession Instances Not Managed by Alamofire

If we could handle the callbacks in this repo, we could send them out.

**Comment by winkelsdorf** [comment]
They are available in Alamofire's Notifications.swift.

This repo could reference them with the namespace:
```
public struct Notifications {
    /// Used as a namespace for all `NSURLSessionTask` related notifications.
    public struct Task {
        /// Notification posted when an `NSURLSessionTask` is resumed. The notification `object` contains the resumed
        /// `NSURLSessionTask`.
        public static let DidResume = "com.alamofire.notifications.task.didResume"

        /// Notification posted when an `NSURLSessionTask` is suspended. The notification `object` contains the 
        /// suspended `NSURLSessionTask`.
        public static let DidSuspend = "com.alamofire.notifications.task.didSuspend"

        /// Notification posted when an `NSURLSessionTask` is cancelled. The notification `object` contains the
        /// cancelled `NSURLSessionTask`.
        public static let DidCancel = "com.alamofire.notifications.task.didCancel"

        /// Notification posted when an `NSURLSessionTask` is completed. The notification `object` contains the
        /// completed `NSURLSessionTask`.
        public static let DidComplete = "com.alamofire.notifications.task.didComplete"
    }
}```

**Comment by kean** [comment]
Yeah, that what I was going to suggest too. Alamofire is inconsistent with those notifications though. Some of them are sent from `Alamofire.Request` but `Alamofire.NotificationsTask.DidComplete` is sent from `Alamofire.Manager` - so this one should get sent even in the current Nuke implementation.

**Comment by kean** [comment]
`Alamofire.NetworkActivityIndicatorManager` listens to three of those notifications:

- Notifications.Task.DidResume
- Notifications.Task.DidSuspend
- Notifications.Task.DidComplete

So you should only figure out how to send the first one (DidResume).

**Comment by winkelsdorf** [comment]
Right, ```Alamofire.NotificationsTask.DidComplete``` always gets through. The other two are missing.

What I would need to check is if there is a way to always send them from Nuke, without implementing them each and everywhere on my own..

What about implementing a stub NotificationProtocol in Nuke and make it a property of the ImageManager (but not in the public init)?

**Comment by kean** [comment]
I would suggest to make a subclass `Nuke.AlamofireImageDataLoader`, override method that creates an `NSURLSessionTask` and add a KVO observer on task's `state` property and continue from there.

```
NOTE

All task properties support key-value observing.
```

I think that's what `Alamofire` should've done in the first place.

**Comment by winkelsdorf** [comment]
Good catch! I'll give it a try 👍

**Comment by kean** [comment]
You could also give [AlamofireImage](https://github.com/Alamofire/AlamofireImage) a try and avoid all the pain.

**Comment by winkelsdorf** [comment]
One easy solution, obvious ^^ 

I was trying to stick to Nuke because I wanted Preheating in other Views. Until a few minutes ago I thought that your Preheating component relies on Nuke, until I checked the Nuke Demo. But the repo is already very clear about:

> You can use Preheat in conjunction with any image loading library including Nuke which it was designed for

What would you say, leave this open and tag it as feature reuest? Something that can be kept in mind when doing a major API change in a future release?

**Comment by kean** [comment]
> What would you say, leave this open and tag it as feature reuest? Something that can be kept in mind when doing a major API change in a future release?

Yes, please, leave it open for now. I'll give it some more thought later.

> Edit: The real implementation of the preheating is done in Nuke, so using Alamofire+Preheat creates a little boilerplate, too.

That's true. Well, it's all up to you :)

**Comment by winkelsdorf** [comment]
Ok, leaving it open.

Haha, you are absolutely right. Well I liked what I read and saw about Nuke, so I am going to use it ;)

A little quick-n-dirty implementation which works even with KVO, subclasssing AlamofireImageDataLoader as sugested:
```
import UIKit
import Alamofire
import Nuke
import NukeAlamofirePlugin

class AlamofireImageDataLoaderWithNetworkActivityIndicator: AlamofireImageDataLoader {

    // MARK: ImageDataLoading

    /** Creates a request using Alamofire.Manager and returns an NSURLSessionTask which is managed by Alamofire.Manager.
     */
    override func taskWith(request: ImageRequest, progress: ImageDataLoadingProgress, completion: ImageDataLoadingCompletion) -> NSURLSessionTask {
        let task = self.manager.request(request.URLRequest)
        NSNotificationCenter.defaultCenter().postNotificationName(Notifications.Task.DidResume, object: task)

        task.response { (_, response, data, error) -> Void in
            NSNotificationCenter.defaultCenter().postNotificationName(Notifications.Task.DidComplete, object: task)
            completion(data: data, response: response, error: error)
            }.progress { (_, totalBytesReceived, totalBytesExpected) -> Void in
                progress(completed: totalBytesReceived, total: totalBytesExpected)
        }
        return task.task
    }

}
```

First test is working.

As long as I can assume that even a cancelled or aborted task invokes the completion() handler everything should work as expected.

**Comment by kean** [comment]
> As long as I can assume that even a cancelled or aborted task invokes the completion() handler everything should work as expected.

Tasks are added to a queue. They might never get resumed.

**Comment by winkelsdorf** [comment]
Hmm, I see. And the other way round: If I leave the bundling out, just use Nuke for all the Image Handling - how would you implement a global Network Activity Indicator? Is there something I can observe with KVO on ImageManager.shared?

Btw. noticed that even if I replace ImageManager.shared = ImageManager(configuration: ImageManagerConfiguration(dataLoader: dataLoader)) at the very beginning in didFinishLaunchingWithOptions, the Nuke Cache folder gets created.

**Comment by kean** [comment]
> how would you implement a global Network Activity Indicator?

I would go with a KVO observing (using some helper library) on NSURLSessionTask's state ^^

> the Nuke Cache folder gets created.

I guess the default manager always gets created some time during the initialization of `ImageManager` class:

```swift
/// Manages shared ImageManager instance.
public extension ImageManager {
    private static var manager = ImageManager()
```

**Comment by winkelsdorf** [comment]
> I would go with a KVO observing (using some helper library) on NSURLSessionTask's state ^^

Haha. Yeah, and discover how crash prone KVO on NSURLSessionTask actually is: 
https://github.com/AFNetworking/AFNetworking/issues/1477

Somebody points out there that it's confirmed by Apple Engineering to be a bug in KVO (not NSUrlSessionTask itself).

There are several threads on SO and Radars open too 😬 I am currently not sure, if I really want to go down that road and try it myself. Looks like a great waste of time, even if it might be fixed for some iOS 9.x versions, iOS 8 is broken.

Hmm, what do you think about opening an Issue on the Nuke repo:
The HIG states, that Network Activity that takes longer that a few seconds should show the Network Activity Indicator. Preheating would likely take longer.

> Display the network activity indicator to provide feedback when your app accesses the network for more than a couple of seconds. If the operation finishes sooner than that, you don’t have to show the network activity indicator, because the indicator is likely to disappear before users notice its presence.

Probably something worth to consider in the main repo?

**Comment by winkelsdorf** [comment]
Something like this works, of course Nuke would need it's own notifications, or a property in the shared manager. Plenty of easy possibilities.

Testcode in Nuke`s Internal.swift:

```
func resume(task: NSURLSessionTask) {
        if !pendingTasks.containsObject(task) && !executingTasks.contains(task) {
            pendingTasks.addObject(task)
            setNeedsExecute()
            NSNotificationCenter.defaultCenter().postNotificationName(Notifications.Task.DidResume, object: task)
        }
    }
    
    func cancel(task: NSURLSessionTask) {
        if pendingTasks.containsObject(task) {
            pendingTasks.removeObject(task)
        } else if executingTasks.contains(task) {
            executingTasks.remove(task)
            task.cancel()
            setNeedsExecute()
            NSNotificationCenter.defaultCenter().postNotificationName(Notifications.Task.DidCancel, object: task)
        }
    }
    
    func finish(task: NSURLSessionTask) {
        if pendingTasks.containsObject(task) {
            pendingTasks.removeObject(task)
        } else if executingTasks.contains(task) {
            executingTasks.remove(task)
            setNeedsExecute()
            NSNotificationCenter.defaultCenter().postNotificationName(Notifications.Task.DidComplete, object: task)
        }
    }
```

That works, but I am not quite sure about the positions. Need to have a deeper look at your setNeedsExecute() logic.

**Comment by kean** [comment]
> Haha. Yeah, and discover how crash prone KVO on NSURLSessionTask actually is: 
AFNetworking/AFNetworking#1477

> Somebody points out there that it's confirmed by Apple Engineering to be a bug in KVO (not NSUrlSessionTask itself).

Hmm, I see, thanks for sharing this. Now I know why AFNetworking has those dangerous resume/cancel swizzles.

> Something like this works, of course Nuke would need it's own notifications, or a property in the shared manager. Plenty of easy possibilities.

Yeah, I think I could easily implement and release this.

**Comment by winkelsdorf** [comment]
> Hmm, I see, thanks for sharing this. Now I know why AFNetworking has those dangerous resume/cancel swizzles.
You're welcome! Thank you for this great brainstorming!

> Yeah, I think I could easily implement and release this.
That would be a great help in this use case 👍 

Of course TaskManager is very elegant right now, with no coupling to the ImageManger (reusable for anything else). But here it's only used for Nuke, so it could take advantage from.

From the design perspective, TaskManager could be left isolated by sending internal Notifications (something like com.github.kean.taskmanager.didResume etc) which are in turn consumed by ImageManager. 

The ImageManager can get a new property for a Notification property pointing to a default struct (containing the strings for sending like in Alamofire Notifications, here com.github.kean.nuke.didResume etc).

If ImageManager.notifications's struct get's replaced, other notifications (i.e. Alamofire) are sent.

What do you think?

**Comment by kean** [comment]
Ok, I'll add those notifications sometime soon.

> If ImageManager.notifications's struct gets replaced, other notifications (i.e. Alamofire) are sent automatically.

This doesn't really sound right, why would Nuke send Alamofire notifications? This might cause unexpected problems. You could easily observe Nuke notifications and send Alamofire notifications (remember, `Alamofire.Notifications.Task.DidComplete` already gets send).

**Comment by winkelsdorf** [comment]
> This doesn't really sound right, why would Nuke send Alamofire notifications? This might cause unexpected problems. You could easily observe Nuke notifications and send Alamofire notifications (remember, Alamofire.Notifications.Task.DidComplete already gets send).

I meant allow your users replacing the struct by setting a property. So it could basically send whatever they want. 

**But** having a 2nd fresh thought about: I agree, don't overcomplicate things. A simple implementation sending Nuke's own notifications is absolutely sufficient.

Handling them (and forward in this scenario) is easy.

Thank you 👍

**Comment by kean** [comment]
Added three basic notifications in https://github.com/kean/Nuke/releases/tag/3.1.0. Just forward `Nuke.SessionTaskDidResumeNotification` to `AlamofireNetworkActivityIndicator` and you should be good to go.

I'm planning to rethink Alamofire integration for Nuke 4.0 (but that's *not* the nearest future).

**Comment by winkelsdorf** [comment]
Working like a charm, thank you very much 👍 

If it's useful for anybody else, I just setup a simple singleton wrapper:
```swift
import Foundation
import Alamofire
import Nuke

// Wrapper for handling notifications from Nuke with Alamofire's NetworkActivityIndicator
class NetworkActivityIndicatorWrapper {

    static let sharedInstance = NetworkActivityIndicatorWrapper()
    private init() {} // singleton, prevent use of default () initializer for this class

    func configure() {
        NSNotificationCenter.defaultCenter().addObserver(self, selector: #selector(receivedNukeNotification(_:)), name: Nuke.SessionTaskDidResumeNotification, object: nil)
        NSNotificationCenter.defaultCenter().addObserver(self, selector: #selector(receivedNukeNotification(_:)), name: Nuke.SessionTaskDidCancelNotification, object: nil)
        NSNotificationCenter.defaultCenter().addObserver(self, selector: #selector(receivedNukeNotification(_:)), name: Nuke.SessionTaskDidCompleteNotification, object: nil)
    }

    deinit {
        NSNotificationCenter.defaultCenter().removeObserver(self, name: Nuke.SessionTaskDidResumeNotification, object: nil)
        NSNotificationCenter.defaultCenter().removeObserver(self, name: Nuke.SessionTaskDidCancelNotification, object: nil)
        NSNotificationCenter.defaultCenter().removeObserver(self, name: Nuke.SessionTaskDidCompleteNotification, object: nil)
    }

    @objc func receivedNukeNotification(notification: NSNotification) {
        switch notification.name {
        case Nuke.SessionTaskDidResumeNotification:
            NSNotificationCenter.defaultCenter().postNotificationName(Alamofire.Notifications.Task.DidResume, object: nil)
        case Nuke.SessionTaskDidCancelNotification:
            NSNotificationCenter.defaultCenter().postNotificationName(Alamofire.Notifications.Task.DidCancel, object: nil)
        case Nuke.SessionTaskDidCompleteNotification:
            NSNotificationCenter.defaultCenter().postNotificationName(Alamofire.Notifications.Task.DidComplete, object: nil)
        default:
            break
        }
    }

}
```

Setup together with Alamofire's NetworkActivityIndicator with:
```swift
        // Automatically show Network Activity Indicator when using Alamofire
        NetworkActivityIndicatorManager.sharedManager.startDelay = 0
        NetworkActivityIndicatorManager.sharedManager.isEnabled = true

        // Attach Nuke to NetworkActivityIndicatorManager
        NetworkActivityIndicatorWrapper.sharedInstance.configure()
```

**Comment by kean** [comment]
@winkelsdorf I'm working on Nuke 4 which resolves this issue (along many others). It will feature full Alamofire support. Release soon.

**Comment by winkelsdorf** [comment]
@kean Thanks for the notification! That sounds promising, I am going to have a deeper look into Nuke 4 soon. I assume the integration of the network activity will then be handled by the Nuke-Alamofire-Plugin?

**Comment by kean** [comment]
@winkelsdorf `AlamofireNetworkActivityIndicator` just works now. Nuke 4 uses `resume()` and `cancel()` methods of `Alamofire.Request` like it should. I hope to release Nuke 4.0 today/tomorrow. In the meantime it would be great if you could test this with current beta (Nuke 4.0-beta3).

**Comment by winkelsdorf** [comment]
@kean Sounds perfect to me! Sure, no problem. I am testing this together with other things right now - I am trying to migrate a working project to Swift 3 now.

**Comment by kean** [comment]
@winkelsdorf good luck with that :finnadie:

**Comment by winkelsdorf** [comment]
@kean I know what you mean, been on this for 1,5 days now 🙈😂

**Comment by winkelsdorf** [comment]
@kean Your latest commit to the swift3 podspec broke the CocoaPods use, please see my comment to the commit (`"s.dependency 'Nuke', '~> 4.0'"` imo needs to be adjusted for Nuke 4 while at 4.0-beta3?).

**Comment by kean** [comment]
Yeah, you are right. Fixed. I was preparing it for a release today, but then decided that I need one more day.

You are also going to need to install Nuke from `master`, a not tagged `4.0-beta3`- there was one breaking change yesterday. 

Sorry, it's a mess right now 😄Complexity of working on multiple dependant modules 😄

**Comment by winkelsdorf** [comment]
No Problem, really! I do understand that's a lot of work and complexity right now. In a couple of weeks things will stabilize for you hopefully 😄

**Comment by kean** [comment]
Just pushed Nuke 4.0 and Nuke-Alamofire-Plugin 1.0 specs 🚀

**Comment by winkelsdorf** [comment]
Great to hear that, you also already bumped Preheat 👍

I'll give you feedback in a couple of days :)

**Comment by kean** [comment]
Awesome, hope it works well for you.
