### ISSUE TITLE
Issue with Alamofire Activity Indicator: Spinner does not stop automatically

### ISSUE THREAD

**Issue by winkelsdorf** [kean/Nuke-Alamofire-Plugin#7]
Hi Alexander, 

as you know I am using ```AlamofireNetworkActivityIndicator``` to get automatic indicator handling. I noticed that the spinner does not stop anymore when using the latest Alamofire, AlamofireNetworkActivityIndicator, Nuke and Nuke-Alamofire-Plugin.

Currently investigating what's going on.

My code to route Nuke through Alamofire (in AppDelegate):
```swift
        // Automatically show Network Activity Indicator for Alamofire
        NetworkActivityIndicatorManager.shared.isEnabled = true

        // Redirect Nuke through Alamofire
        let loader = Nuke.Loader(loader: NukeAlamofirePlugin.DataLoader(), 
            decoder: Nuke.DataDecoder(), cache: Nuke.Cache.shared)
        let manager = Nuke.Manager(loader: loader, cache: Nuke.Cache.shared)
        Nuke.Manager.shared = manager
```

The code loading an example image:
```swift
    func loadRemoteImage(url: URL) {
        if imageLoaded {
            return
        }

        let request = Request(urlRequest: URLRequest(url: url))

        Nuke.loadImage(with: request, into: imageView) { [weak self] response, isFromMemCache in
            guard let strongSelf = self else {
                return
            }

            switch response {
            case let .fulfilled(image):
                strongSelf.gradientEnabled = true
                UIView.transition(with: strongSelf, duration: isFromMemCache ? 0.0 : 0.10,
                                  options: [.transitionCrossDissolve], animations: {
                    strongSelf.imageView.image = image.faceZoomedImage()
                }, completion: nil)
                strongSelf.imageLoaded = true
            case .rejected:
                strongSelf.setPlaceHolder()
                strongSelf.imageLoaded = false
            }
        }
    }
```

Releases are latest tags from CocoaPods specs, but not :head.

Cheers,
Frederik

**Comment by kean** [comment]
Hey, @winkelsdorf! I was able to reproduce this in a demo project, will investigate. Thanks for the report!

**Comment by winkelsdorf** [comment]
@kean You're very welcome :) I had a chance to look into all the changes - stunning 👍 Thank you for your hard work!

**Comment by kean** [comment]
@winkelsdorf thanks, that's the best motivation to keep improving 😉 

I found an issue. I keep forgetting that Alamofire automatically starts requests: `if startRequestsImmediately { request.resume() }`. My `DataLoader` also resumes requests. As a result requests gets resumed twice. And the `resume()` method in Alamofire doesn't account for that:

```swift
    /// Resumes the request.
    open func resume() {
        guard let task = task else { delegate.queue.isSuspended = false ; return }

        if startTime == nil { startTime = CFAbsoluteTimeGetCurrent() }

        task.resume()

        NotificationCenter.default.post(
            name: Notification.Name.Task.DidResume,
            object: self,
            userInfo: [Notification.Key.Task: task]
        )
    }
```

So the `Notification.Name.Task.DidResume` gets fired twice with just a single `Notification.Name.Task.DidComplete`.

**Comment by winkelsdorf** [comment]
@kean I know what you are speaking of. With Swift3 now I took the long way to improve the code base of my current project and refactored/rewrote some things. Removed a lot of clutter, especially for older iOS versions. Seeing my own "older" code is sometimes distracting as with the improvements I made I would do things different now.. Clean Code Developers are always starting to learn again and again ;)

Regarding the issue: Good catch 👍 One of those logical bugs.. Thanks for solving it so quickly 😁

**Comment by winkelsdorf** [comment]
Verified the fix to be working correctly :) Thanks 👍

**Comment by kean** [comment]
Awesome, hope you find more issues 😄

**Comment by kean** [comment]
I'm glad that activity indicator is finally working, and does not require any workaround. This thing is useful.

**Comment by winkelsdorf** [comment]
Yes, definitely - that's a very convenient way to make use of the indicator automatically. Adding just the two pods and 4 lines to redirect everything 👍 

Haha, I don't expect to find anything more ^^ Anyway, I am going to integrate Preheat for my TableViews in a couple of days, let's see :)

Cheers,
Frederik
