### ISSUE TITLE
Deadlock

### ISSUE THREAD

**Issue by winkelsdorf** [kean/Nuke-Alamofire-Plugin#8]
Hi Alexander,

something more critical than the previous issue: I am getting a deadlock in Nuke as soon as I am routing through Alamofire.

**Steps to reproduce:**

1. Route Nuke in AppDelegate through Alamofire
2. Switch to Homescreen (Multitasking)
3. Switch back to App

**Environment:**
Tested iOS 9.0 and 10.0 Simulators and iPhone 6 with iOS 10

**Expected**:
Working normally

**Actual**:
Deadlock

Code to initialize the Routing:
```swift
        // Redirect Nuke through Alamofire
        let loader = Nuke.Loader(loader: NukeAlamofirePlugin.DataLoader(), 
            decoder: Nuke.DataDecoder(), cache: Nuke.Cache.shared)
        let manager = Nuke.Manager(loader: loader, cache: Nuke.Cache.shared)
        Nuke.Manager.shared = manager
```

Cheers,
Frederik

**Screenshots**

<img width="1055" alt="screenshot 2016-10-04 15 20 25" src="https://cloud.githubusercontent.com/assets/1413291/19075655/275fc050-8a46-11e6-81af-1d3a4f3f79c2.png">
<img width="1246" alt="screenshot 2016-10-04 15 20 42" src="https://cloud.githubusercontent.com/assets/1413291/19075657/278e7b16-8a46-11e6-80d5-5f4f282b3a78.png">

**Comment by kean** [comment]
Such an embarassement 😄 Thanks for the report, [fixed in 4.1.1](https://github.com/kean/Nuke/releases/tag/4.1.1)

**Comment by kean** [comment]
podspec for 4.1.1 is also live

**Comment by winkelsdorf** [comment]
Haha, got you 😄 Working perfectly now with 4.1.1. As always you are damn quick with your fixes 👍
