### ISSUE TITLE
Global Routing

### ISSUE THREAD

**Issue by winkelsdorf** [kean/Nuke-Alamofire-Plugin#9]
Congrats for the Nuke 5 Release! 🍾 This is blazing fast and extremely well designed now 👍 

One thing I noticed, is that the shared Manager and Loader are now `let` constants.

Routing all Traffic through Alamofire globally (i.e. in `AppDelegate`) will not work anymore.

I previously used:
```swift
let loader = Nuke.Loader(loader: NukeAlamofirePlugin.DataLoader(), decoder: Nuke.DataDecoder(), cache: Cache.shared)
let manager = Nuke.Manager(loader: loader, cache: Cache.shared)
Nuke.Manager.shared = manager
```

Of course I could hold a strong reference to my own global shared instance of a routed Manager, but I am wondering what your "best suggested practice" would be? Global reference vs. instantiated on-demand?

Cheers 
Frederik

**Comment by kean** [comment]
Thanks! 

I've decided to make them constants for two reasons:

- It's not a common practice in iOS to have mutable shared instances to inject dependencies.
- Nuke had 3 shared var which made things even more complicated. It was unclear which of them you should replace and when.

Actually making them mutable wasn't a conscious decision 😄 I have no memory why I did it. There never were many reasons to replace shared `Manager`. The only place where it is used in global `loadImage(with:target:)` functions.

>  I am wondering what your "best suggested practice" would be?

**Comment by winkelsdorf** [comment]
Didn't want to disturb you by notifications, so the follow up today.

> I've decided to make them constants for two reasons:
> 
> * It's not a common practice in iOS to have mutable shared instances to inject dependencies.
> * Nuke had 3 shared vars which made things even more complicated. It was unclear which of them you should replace and when.
> 
> Actually making them mutable wasn't a conscious decision 😄 I have no memory why I did it. There never were many reasons to replace shared Manager. The only place where it is used is global loadImage(with:target:) functions.
> 

Agreed.

> > I am wondering what your "best suggested practice" would be?
> I would suggest to add your own global let and create your custom shared Manager there. If you still want to have global loadImage(with:target:) functions just copy them to your project and replace the Manager which they use. The compiler automatically picks declarations from the module scope over the scope of the imported modules.

Ok, good to hear that you suggest the same approach I was initially thinking of 👍 

Thanks again!

Cheers
Frederik

**Comment by winkelsdorf** [comment]
Addendum, instead of copying over (and possibly running into conflicts with future updates), one could use a global constant like this:

```swift
import Nuke
import NukeAlamofirePlugin

// swiftlint:disable:next variable_name
let NukeAlamofire: Nuke.Manager = {
    let loader = NukeAlamofirePlugin.DataLoader()
    let manager = Nuke.Manager(loader: Nuke.Loader(loader: loader), cache: Nuke.Cache.shared)

    return manager
}()
```

This wraps all methods of the manager, too.

Example Usage:
```swift
NukeAlamofire.LoadImage(:) // as before
```

Global constants and variables are always lazy, so we benefit from not instantiating before it's really used.

**Comment by kean** [comment]
Interesting approach!

**Comment by winkelsdorf** [comment]
Thanks!

**Comment by winkelsdorf** [comment]
As a follow-up I can confirm that with your changes and the approach to use a global constant for routing Nuke through Alamofire the leaks mentioned in the issue for the core library (https://github.com/kean/Nuke/issues/99) no longer appear!

Thanks, Alexander!

Cheers
Frederik

<img width="1396" alt="screenshot 2017-02-03 20 40 32" src="https://cloud.githubusercontent.com/assets/1413291/22605642/05f399ee-ea51-11e6-9a24-99deb42e4092.png">
That's the way I like the leak profiler ;)

**Comment by kean** [comment]
Those singletons created in Nuke still show up in Instruments. I've spent at least couple of hours trying different approaches to figure out why.

It seems that global `let` that you used behaves just fine compared to `static let` which I add inside a class declaration:

```swift
public final class Manager {
    public static let shared = Manager(loader: Loader.shared, cache: Cache.shared)
}
```

The good thing about Nuke 5 is that without promises I'm absolutely sure that everything deallocates the moment it is no longer needed. Generational analysis also shows that there are no apparent problems.

Thanks for testing this out!

**Comment by winkelsdorf** [comment]
> It seems that global let that you used behaves just fine compared to static let which I add inside a class

Thats odd, but I would say it's instruments to blame as it's obviously done correctly in your code

> The good thing about Nuke 5 is that without promises I'm absolutely sure that everything deallocates the moment it is no longer needed. Generational analysis also shows that there are no apparent problems

And it performs excellent. I really like the way you simplified the code even more 👍
